#!/bin/sh
FROM alpine
RUN apk update ; apk add openjdk11 ;
COPY ./tweetoscope/target/HashtagCounter-jar-with-dependencies.jar .	
ENV number=5
ENV HOSTNAME=kafka-service
ENV PORT=9092
ENV SERVER=kafka-service:9092
CMD echo ${SERVER}
CMD java -jar HashtagCounter-jar-with-dependencies.jar ${SERVER} Extractor Counter ${number}
