version: '3,3'
services:
  zookeeper_local_dev:
    image: wurstmeister/zookeeper    
    container_name: zookeeper_local_dev    
    ports:    
      - "2181:2181"
  kafka_local_dev_1:
    image: wurstmeister/kafka
    hostname: kafka-service
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: kafka-service
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_local_dev:2181
      KAFKA_LISTENERS: INTERNAL://kafka-service:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-service:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CREATE_TOPICS: "Tweet:4:2,Filter:4:2,Extractor:2:2,Counter:2:2"
    depends_on:
      - zookeeper_local_dev
  kafka_local_dev_2:
    image: wurstmeister/kafka
    hostname: kafka-service-2
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ADVERTISED_HOST_NAME: kafka-service-2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_local_dev:2181
      KAFKA_LISTENERS: INTERNAL://kafka-service-2:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-service-2:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    depends_on:
      - zookeeper_local_dev

  filter:
    image: maxlamenace34/tweetoscope_compose:emptyfilter
    environment:
      SERVER: kafka-service:9092
    depends_on:
      kafka_local_dev_1:
        condition: service_started
  filter-2:
    image: maxlamenace34/tweetoscope_compose:emptyfilter
    environment:
      SERVER: kafka-service:9092
    depends_on:
      kafka_local_dev_1:
        condition: service_started
  extractor:
    image: maxlamenace34/tweetoscope_compose:extractor
    environment:
      SERVER: kafka-service:9092
    depends_on:
      kafka_local_dev_1:
        condition: service_started
  extractor-2:
    image: maxlamenace34/tweetoscope_compose:extractor
    environment:
      SERVER: kafka-service:9092
    depends_on:
      kafka_local_dev_1:
        condition: service_started
  counter:
    image: maxlamenace34/tweetoscope_compose:counter
    environment:
      SERVER: kafka-service:9092
      number: 5
    depends_on:
      kafka_local_dev_1:
        condition: service_started
   producer:
    image: maxlamenace34/tweetoscope_compose:producerdatabase
    environment:
      SERVER: kafka-service:9092
    depends_on:
      kafka_local_dev_1:
        condition: service_started

