#!/bin/sh
FROM alpine
RUN apk update ; apk add openjdk11 ;
COPY ./tweetoscope/target/EmptyTweetFilter-jar-with-dependencies.jar .
CMD java -jar EmptyTweetFilter-jar-with-dependencies.jar localhost:9092 Tweet Filter
